export type SeoPage = {
  pageTitle: string;
  pageSlug: string;
  primaryKeyword: string;
  secondaryKeywords: string;
  targetArea: string;
  pageType: string;
  searchIntent: string;
  volumePerMonth: string;
  keywordDifficulty: string;
  cpc: string;
  priority: string;
  ctaStrategy: string;
};

export const SITE_NAME = "Grease Guard Pros";
export const DEFAULT_SITE_URL = "https://greaseguardpros.com";
export const PHONE_DISPLAY = "1-888-328-8990";
export const PHONE_E164 = "+18883208990";

export const SEO_PAGES: SeoPage[] = [
  {
    pageTitle: "Commercial Kitchen Exhaust Cleaning Services",
    pageSlug: "/kitchen-exhaust-cleaning",
    primaryKeyword: "kitchen exhaust cleaning",
    secondaryKeywords: "commercial kitchen exhaust cleaning, kitchen exhaust cleaning services, kitchen exhaust duct cleaning, exhaust hood cleaning, kitchen exhaust system cleaning",
    targetArea: "Canada (National)",
    pageType: "Service Pillar",
    searchIntent: "Commercial",
    volumePerMonth: "200.0",
    keywordDifficulty: "4.0",
    cpc: "3.0",
    priority: "High",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Commercial Hood Cleaning Services | NFPA 96 Certified",
    pageSlug: "/hood-cleaning-services",
    primaryKeyword: "hood cleaning services",
    secondaryKeywords: "commercial hood cleaning, restaurant hood cleaning, kitchen hood cleaning, hood cleaning company, certified hood cleaning company",
    targetArea: "Canada (National)",
    pageType: "Service Pillar",
    searchIntent: "Commercial",
    volumePerMonth: "350.0",
    keywordDifficulty: "3.0",
    cpc: "1.5",
    priority: "Top Priority",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Hood Fan & Exhaust Fan Cleaning Services",
    pageSlug: "/hood-fan-cleaning",
    primaryKeyword: "hood fan cleaning",
    secondaryKeywords: "kitchen exhaust fan cleaning, exhaust fan cleaning, range hood cleaning, hood vent cleaning, kitchen hood fan cleaning",
    targetArea: "Canada (National)",
    pageType: "Service Pillar",
    searchIntent: "Commercial",
    volumePerMonth: "90.0",
    keywordDifficulty: "1.0",
    cpc: "1.0",
    priority: "Medium",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Grease Trap Cleaning & Pumping Services",
    pageSlug: "/grease-trap-cleaning",
    primaryKeyword: "grease trap cleaning",
    secondaryKeywords: "commercial grease trap cleaning, grease trap pumping, grease trap service, grease interceptor cleaning, grease trap maintenance",
    targetArea: "Canada (National)",
    pageType: "Service Pillar",
    searchIntent: "Commercial",
    volumePerMonth: "600.0",
    keywordDifficulty: "0.0",
    cpc: "2.5",
    priority: "Top Priority",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Catch Basin Cleaning Services | Commercial & Parking Lot",
    pageSlug: "/catch-basin-cleaning",
    primaryKeyword: "catch basin cleaning",
    secondaryKeywords: "catch basin cleaning services, catch basin cleaning companies, commercial catch basin cleaning, parking lot catch basin cleaning, storm drain cleaning",
    targetArea: "Canada (National)",
    pageType: "Service Pillar",
    searchIntent: "Commercial",
    volumePerMonth: "400.0",
    keywordDifficulty: "0.0",
    cpc: "3.0",
    priority: "Top Priority",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Lift Station & Sump Pit Cleaning & Maintenance",
    pageSlug: "/lift-station-sump-pit-cleaning",
    primaryKeyword: "lift station cleaning",
    secondaryKeywords: "sump pit cleaning, lift station maintenance, sewage lift station cleaning, sump pit maintenance, wet well cleaning",
    targetArea: "Canada (National)",
    pageType: "Service Pillar",
    searchIntent: "Commercial",
    volumePerMonth: "50.0",
    keywordDifficulty: "1.0",
    cpc: "2.0",
    priority: "High",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Preventative Hydro Jetting Services | Drain & Sewer",
    pageSlug: "/hydro-jetting-services",
    primaryKeyword: "hydro jetting services",
    secondaryKeywords: "hydro jetting, preventative hydro jetting, hydro jetting drain cleaning, sewer jetting, drain hydro jetting, hydro jetting plumbing",
    targetArea: "Canada (National)",
    pageType: "Service Pillar",
    searchIntent: "Transactional",
    volumePerMonth: "200.0",
    keywordDifficulty: "0.0",
    cpc: "8.0",
    priority: "Top Priority",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Commercial Kitchen Deep Cleaning Services",
    pageSlug: "/commercial-kitchen-cleaning",
    primaryKeyword: "commercial kitchen cleaning services",
    secondaryKeywords: "commercial kitchen cleaning, commercial kitchen deep cleaning, restaurant kitchen cleaning, commercial kitchen cleaning company",
    targetArea: "Canada (National)",
    pageType: "Service Pillar",
    searchIntent: "Commercial",
    volumePerMonth: "200.0",
    keywordDifficulty: "0.0",
    cpc: "2.0",
    priority: "High",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Grease Trap Installation Services | Commercial Kitchens",
    pageSlug: "/grease-trap-installation",
    primaryKeyword: "grease trap installation",
    secondaryKeywords: "grease interceptor installation, commercial grease trap installation, grease trap replacement, grease trap install",
    targetArea: "Canada (National)",
    pageType: "Service Pillar",
    searchIntent: "Commercial",
    volumePerMonth: "150.0",
    keywordDifficulty: "0.0",
    cpc: "1.7",
    priority: "High",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Hood Cleaning Service Near Me | Same-Day",
    pageSlug: "/hood-cleaning-near-me",
    primaryKeyword: "hood cleaning service near me",
    secondaryKeywords: "hood cleaning near me, hood cleaning services near me, commercial hood cleaning near me, vent hood cleaning near me",
    targetArea: "Canada (National)",
    pageType: "Near Me Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "500.0",
    keywordDifficulty: "2.0",
    cpc: "1.7",
    priority: "Top Priority",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Hydro Jetting Near Me | Drain & Sewer Jetting",
    pageSlug: "/hydro-jetting-near-me",
    primaryKeyword: "hydro jetting near me",
    secondaryKeywords: "hydro jetting services near me, hydro jetting service near me, drain jetting near me",
    targetArea: "Canada (National)",
    pageType: "Near Me Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "800.0",
    keywordDifficulty: "0.0",
    cpc: "1.5",
    priority: "Top Priority",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Grease Trap Cleaning Near Me | Commercial",
    pageSlug: "/grease-trap-cleaning-near-me",
    primaryKeyword: "grease trap cleaning near me",
    secondaryKeywords: "grease trap service near me, grease trap pumping near me, commercial grease trap cleaning near me",
    targetArea: "Canada (National)",
    pageType: "Near Me Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "150.0",
    keywordDifficulty: "0.0",
    cpc: "3.5",
    priority: "High",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Catch Basin Cleaning Near Me",
    pageSlug: "/catch-basin-cleaning-near-me",
    primaryKeyword: "catch basin cleaning near me",
    secondaryKeywords: "catch basin cleaning services near me, storm drain cleaning near me, parking lot drain cleaning near me",
    targetArea: "Canada (National)",
    pageType: "Near Me Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "90.0",
    keywordDifficulty: "0.0",
    cpc: "1.3",
    priority: "High",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Hydro Jetting Cost in Canada | Pricing Guide",
    pageSlug: "/hydro-jetting-cost",
    primaryKeyword: "hydro jetting cost",
    secondaryKeywords: "how much does hydro jetting cost, hydro jetting price, drain jetting cost, sewer jetting cost",
    targetArea: "Canada (National)",
    pageType: "Cost Guide",
    searchIntent: "Commercial",
    volumePerMonth: "80.0",
    keywordDifficulty: "0.0",
    cpc: "1.5",
    priority: "Medium",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Grease Trap Installation Cost | Pricing Guide",
    pageSlug: "/grease-trap-installation-cost",
    primaryKeyword: "grease trap installation cost",
    secondaryKeywords: "grease trap cost, grease trap price, grease interceptor cost, grease trap replacement cost",
    targetArea: "Canada (National)",
    pageType: "Cost Guide",
    searchIntent: "Commercial",
    volumePerMonth: "70.0",
    keywordDifficulty: "0.0",
    cpc: "1.0",
    priority: "Medium",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Hood & Kitchen Exhaust Cleaning Toronto",
    pageSlug: "/hood-cleaning-toronto",
    primaryKeyword: "hood cleaning toronto",
    secondaryKeywords: "kitchen exhaust cleaning toronto, restaurant hood cleaning toronto, commercial hood cleaning toronto",
    targetArea: "Toronto, ON",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "80.0",
    keywordDifficulty: "4.0",
    cpc: "1.0",
    priority: "Top Priority",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Catch Basin Cleaning Toronto | Parking Lot & Storm Drains",
    pageSlug: "/catch-basin-cleaning-toronto",
    primaryKeyword: "catch basin cleaning toronto",
    secondaryKeywords: "parking lot catch basin cleaning toronto, storm drain cleaning toronto, commercial catch basin cleaning toronto",
    targetArea: "Toronto, ON",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "40.0",
    keywordDifficulty: "0.0",
    cpc: "6.0",
    priority: "Top Priority",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Hydro Jetting Toronto | Drain & Sewer Jetting",
    pageSlug: "/hydro-jetting-toronto",
    primaryKeyword: "hydro jetting toronto",
    secondaryKeywords: "hydro jetting service toronto, drain jetting toronto, sewer jetting toronto",
    targetArea: "Toronto, ON",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "150.0",
    keywordDifficulty: "2.0",
    cpc: "2.0",
    priority: "Top Priority",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Grease Trap Cleaning Toronto | Commercial Kitchens",
    pageSlug: "/grease-trap-cleaning-toronto",
    primaryKeyword: "grease trap cleaning toronto",
    secondaryKeywords: "commercial grease trap cleaning toronto, grease trap pumping toronto, grease trap service toronto",
    targetArea: "Toronto, ON",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "30.0",
    keywordDifficulty: "18.0",
    cpc: "3.5",
    priority: "High",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Grease Trap Installation Toronto",
    pageSlug: "/grease-trap-installation-toronto",
    primaryKeyword: "grease trap installation toronto",
    secondaryKeywords: "grease interceptor installation toronto, commercial grease trap installation toronto",
    targetArea: "Toronto, ON",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "60.0",
    keywordDifficulty: "1.0",
    cpc: "1.7",
    priority: "High",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Hood Cleaning Mississauga | Restaurant Kitchen Exhaust",
    pageSlug: "/hood-cleaning-mississauga",
    primaryKeyword: "hood cleaning mississauga",
    secondaryKeywords: "kitchen exhaust cleaning mississauga, restaurant hood cleaning mississauga, commercial hood cleaning mississauga",
    targetArea: "Mississauga, ON",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "50.0",
    keywordDifficulty: "2.0",
    cpc: "1.0",
    priority: "High",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Catch Basin Cleaning Mississauga",
    pageSlug: "/catch-basin-cleaning-mississauga",
    primaryKeyword: "catch basin cleaning mississauga",
    secondaryKeywords: "parking lot catch basin cleaning mississauga, storm drain cleaning mississauga",
    targetArea: "Mississauga, ON",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "30.0",
    keywordDifficulty: "0.0",
    cpc: "3.0",
    priority: "High",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Grease Trap Installation Mississauga",
    pageSlug: "/grease-trap-installation-mississauga",
    primaryKeyword: "grease trap installation mississauga",
    secondaryKeywords: "grease interceptor installation mississauga, commercial grease trap mississauga",
    targetArea: "Mississauga, ON",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "30.0",
    keywordDifficulty: "1.0",
    cpc: "1.7",
    priority: "High",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Grease Trap Installation Scarborough",
    pageSlug: "/grease-trap-installation-scarborough",
    primaryKeyword: "grease trap installation scarborough",
    secondaryKeywords: "scarborough grease trap installation, grease interceptor installation scarborough",
    targetArea: "Scarborough, ON",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "60.0",
    keywordDifficulty: "1.0",
    cpc: "1.7",
    priority: "High",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Grease Trap Installation Markham",
    pageSlug: "/grease-trap-installation-markham",
    primaryKeyword: "grease trap installation markham",
    secondaryKeywords: "grease interceptor installation markham, commercial grease trap markham",
    targetArea: "Markham, ON",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "40.0",
    keywordDifficulty: "1.0",
    cpc: "1.7",
    priority: "High",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Grease Trap Installation Brampton",
    pageSlug: "/grease-trap-installation-brampton",
    primaryKeyword: "grease trap installation brampton",
    secondaryKeywords: "brampton grease trap installation, grease interceptor installation brampton",
    targetArea: "Brampton, ON",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "30.0",
    keywordDifficulty: "1.0",
    cpc: "1.7",
    priority: "High",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Catch Basin Cleaning Etobicoke",
    pageSlug: "/catch-basin-cleaning-etobicoke",
    primaryKeyword: "catch basin cleaning etobicoke",
    secondaryKeywords: "parking lot catch basin cleaning etobicoke, storm drain cleaning etobicoke",
    targetArea: "Etobicoke, ON",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "30.0",
    keywordDifficulty: "0.0",
    cpc: "3.0",
    priority: "High",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Commercial Kitchen Cleaning Ottawa | Hood & Exhaust",
    pageSlug: "/commercial-kitchen-cleaning-ottawa",
    primaryKeyword: "commercial kitchen cleaning ottawa",
    secondaryKeywords: "restaurant kitchen cleaning ottawa, hood cleaning ottawa, kitchen exhaust cleaning ottawa",
    targetArea: "Ottawa, ON",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "40.0",
    keywordDifficulty: "1.0",
    cpc: "2.0",
    priority: "High",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Hydro Jetting Kingston | Drain & Sewer Jetting",
    pageSlug: "/hydro-jetting-kingston",
    primaryKeyword: "hydro jetting kingston",
    secondaryKeywords: "hydro jetting service kingston, drain jetting kingston, sewer jetting kingston",
    targetArea: "Kingston, ON",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "100.0",
    keywordDifficulty: "1.0",
    cpc: "1.5",
    priority: "Top Priority",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Hydro Jetting Hamilton | Drain & Sewer Jetting",
    pageSlug: "/hydro-jetting-hamilton",
    primaryKeyword: "hydro jetting hamilton",
    secondaryKeywords: "hydro jetting service hamilton, drain jetting hamilton, sewer jetting hamilton",
    targetArea: "Hamilton, ON",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "30.0",
    keywordDifficulty: "1.0",
    cpc: "1.5",
    priority: "High",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Hydro Jetting London | Drain & Sewer Jetting",
    pageSlug: "/hydro-jetting-london",
    primaryKeyword: "hydro jetting london",
    secondaryKeywords: "hydro jetting service london ontario, drain jetting london, sewer jetting london",
    targetArea: "London, ON",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "40.0",
    keywordDifficulty: "1.0",
    cpc: "1.5",
    priority: "High",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Hydro Jetting Burlington | Drain & Sewer Jetting",
    pageSlug: "/hydro-jetting-burlington",
    primaryKeyword: "hydro jetting burlington",
    secondaryKeywords: "hydro jetting service burlington, drain jetting burlington, sewer jetting burlington",
    targetArea: "Burlington, ON",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "60.0",
    keywordDifficulty: "1.0",
    cpc: "1.5",
    priority: "High",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Hydro Jetting Napanee | Drain & Sewer Jetting",
    pageSlug: "/hydro-jetting-napanee",
    primaryKeyword: "hydro jetting napanee",
    secondaryKeywords: "hydro jetting service greater napanee, drain jetting napanee, sewer jetting napanee",
    targetArea: "Napanee, ON",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "150.0",
    keywordDifficulty: "1.0",
    cpc: "1.5",
    priority: "Top Priority",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Hydro Jetting Gananoque | Drain & Sewer Jetting",
    pageSlug: "/hydro-jetting-gananoque",
    primaryKeyword: "hydro jetting gananoque",
    secondaryKeywords: "hydro jetting service gananoque, drain jetting gananoque, sewer jetting gananoque",
    targetArea: "Gananoque, ON",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "100.0",
    keywordDifficulty: "1.0",
    cpc: "1.5",
    priority: "Top Priority",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Hydro Jetting Brockville | Drain & Sewer Jetting",
    pageSlug: "/hydro-jetting-brockville",
    primaryKeyword: "hydro jetting brockville",
    secondaryKeywords: "hydro jetting service brockville, drain jetting brockville, sewer jetting brockville",
    targetArea: "Brockville, ON",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "80.0",
    keywordDifficulty: "1.0",
    cpc: "1.5",
    priority: "Top Priority",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Hydro Jetting Elgin | Drain & Sewer Jetting",
    pageSlug: "/hydro-jetting-elgin",
    primaryKeyword: "hydro jetting elgin",
    secondaryKeywords: "hydro jetting service elgin, drain jetting elgin, sewer jetting elgin",
    targetArea: "Elgin, ON",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "70.0",
    keywordDifficulty: "1.0",
    cpc: "1.5",
    priority: "High",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Grease Trap Cleaning Mississauga | Commercial Kitchens",
    pageSlug: "/grease-trap-cleaning-mississauga",
    primaryKeyword: "grease trap cleaning mississauga",
    secondaryKeywords: "commercial grease trap cleaning mississauga, grease trap pumping mississauga, grease trap service mississauga",
    targetArea: "Mississauga, ON",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "20.0",
    keywordDifficulty: "0.0",
    cpc: "2.5",
    priority: "High",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Grease Trap Cleaning Hamilton | Commercial Kitchens",
    pageSlug: "/grease-trap-cleaning-hamilton",
    primaryKeyword: "grease trap cleaning hamilton",
    secondaryKeywords: "commercial grease trap cleaning hamilton, grease trap pumping hamilton, grease trap service hamilton",
    targetArea: "Hamilton, ON",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "10.0",
    keywordDifficulty: "0.0",
    cpc: "6.0",
    priority: "Top Priority",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Grease Trap Cleaning Ottawa | Commercial Kitchens",
    pageSlug: "/grease-trap-cleaning-ottawa",
    primaryKeyword: "grease trap cleaning ottawa",
    secondaryKeywords: "commercial grease trap cleaning ottawa, grease trap pumping ottawa, grease trap service ottawa",
    targetArea: "Ottawa, ON",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "20.0",
    keywordDifficulty: "0.0",
    cpc: "2.5",
    priority: "High",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Grease Trap Cleaning Kitchener | Commercial Kitchens",
    pageSlug: "/grease-trap-cleaning-kitchener",
    primaryKeyword: "grease trap cleaning kitchener",
    secondaryKeywords: "commercial grease trap cleaning kitchener, grease trap pumping kitchener, grease trap service kitchener",
    targetArea: "Kitchener, ON",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "10.0",
    keywordDifficulty: "6.0",
    cpc: "0.9",
    priority: "Medium",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Catch Basin Cleaning Scarborough | Parking Lot & Storm Drains",
    pageSlug: "/catch-basin-cleaning-scarborough",
    primaryKeyword: "catch basin cleaning scarborough",
    secondaryKeywords: "parking lot catch basin cleaning scarborough, storm drain cleaning scarborough",
    targetArea: "Scarborough, ON",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "20.0",
    keywordDifficulty: "0.0",
    cpc: "3.0",
    priority: "High",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Catch Basin Cleaning North York | Parking Lot & Storm Drains",
    pageSlug: "/catch-basin-cleaning-north-york",
    primaryKeyword: "catch basin cleaning north york",
    secondaryKeywords: "parking lot catch basin cleaning north york, storm drain cleaning north york",
    targetArea: "North York, ON",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "20.0",
    keywordDifficulty: "0.0",
    cpc: "3.0",
    priority: "High",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Grease Trap Installation Vaughan",
    pageSlug: "/grease-trap-installation-vaughan",
    primaryKeyword: "grease trap installation vaughan",
    secondaryKeywords: "grease interceptor installation vaughan, commercial grease trap vaughan",
    targetArea: "Vaughan, ON",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "30.0",
    keywordDifficulty: "1.0",
    cpc: "1.7",
    priority: "High",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Grease Trap Installation Oakville",
    pageSlug: "/grease-trap-installation-oakville",
    primaryKeyword: "grease trap installation oakville",
    secondaryKeywords: "grease interceptor installation oakville, commercial grease trap oakville",
    targetArea: "Oakville, ON",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "30.0",
    keywordDifficulty: "1.0",
    cpc: "1.7",
    priority: "High",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Grease Trap Installation Newmarket",
    pageSlug: "/grease-trap-installation-newmarket",
    primaryKeyword: "grease trap installation newmarket",
    secondaryKeywords: "grease interceptor installation newmarket, commercial grease trap newmarket",
    targetArea: "Newmarket, ON",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "30.0",
    keywordDifficulty: "1.0",
    cpc: "1.7",
    priority: "High",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Grease Trap Installation Etobicoke",
    pageSlug: "/grease-trap-installation-etobicoke",
    primaryKeyword: "grease trap installation etobicoke",
    secondaryKeywords: "grease interceptor installation etobicoke, commercial grease trap etobicoke",
    targetArea: "Etobicoke, ON",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "10.0",
    keywordDifficulty: "1.0",
    cpc: "1.7",
    priority: "Medium",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Hydro Jetting Barrie | Drain & Sewer Jetting",
    pageSlug: "/hydro-jetting-barrie",
    primaryKeyword: "hydro jetting barrie",
    secondaryKeywords: "hydro jetting service barrie, drain jetting barrie, sewer jetting barrie",
    targetArea: "Barrie, ON",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "10.0",
    keywordDifficulty: "1.0",
    cpc: "1.5",
    priority: "Medium",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Hydro Jetting Cambridge | Drain & Sewer Jetting",
    pageSlug: "/hydro-jetting-cambridge",
    primaryKeyword: "hydro jetting cambridge",
    secondaryKeywords: "hydro jetting service cambridge, drain jetting cambridge, sewer jetting cambridge",
    targetArea: "Cambridge, ON",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "10.0",
    keywordDifficulty: "1.0",
    cpc: "1.5",
    priority: "Medium",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Grease Trap Cleaning Calgary | Commercial Kitchens",
    pageSlug: "/grease-trap-cleaning-calgary",
    primaryKeyword: "grease trap cleaning calgary",
    secondaryKeywords: "commercial grease trap cleaning calgary, grease trap pumping calgary, grease trap service calgary",
    targetArea: "Calgary, AB",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "80.0",
    keywordDifficulty: "0.0",
    cpc: "7.0",
    priority: "Top Priority",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Hydro Jetting Calgary | Drain & Sewer Line Jetting",
    pageSlug: "/hydro-jetting-calgary",
    primaryKeyword: "hydro jetting calgary",
    secondaryKeywords: "hydro jetting sewer line calgary, drain jetting calgary, hydro jetting service calgary",
    targetArea: "Calgary, AB",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "150.0",
    keywordDifficulty: "2.0",
    cpc: "2.0",
    priority: "Top Priority",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Lift Station Cleaning Calgary | Sump Pit & Wet Well",
    pageSlug: "/lift-station-cleaning-calgary",
    primaryKeyword: "lift station cleaning calgary",
    secondaryKeywords: "sump pit cleaning calgary, lift station maintenance calgary, wet well cleaning calgary",
    targetArea: "Calgary, AB",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "50.0",
    keywordDifficulty: "1.0",
    cpc: "2.0",
    priority: "High",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Commercial Kitchen Cleaning Calgary | Hood & Exhaust",
    pageSlug: "/commercial-kitchen-cleaning-calgary",
    primaryKeyword: "commercial kitchen cleaning calgary",
    secondaryKeywords: "commercial kitchen steam cleaning calgary, restaurant kitchen cleaning calgary, hood cleaning calgary",
    targetArea: "Calgary, AB",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "60.0",
    keywordDifficulty: "1.0",
    cpc: "2.0",
    priority: "High",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Kitchen Exhaust Cleaning Calgary | Restaurant Hoods",
    pageSlug: "/kitchen-exhaust-cleaning-calgary",
    primaryKeyword: "kitchen exhaust cleaning calgary",
    secondaryKeywords: "restaurant hood cleaning calgary, commercial kitchen exhaust cleaning calgary",
    targetArea: "Calgary, AB",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "30.0",
    keywordDifficulty: "2.0",
    cpc: "2.5",
    priority: "High",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Grease Trap Cleaning Edmonton | Commercial Kitchens",
    pageSlug: "/grease-trap-cleaning-edmonton",
    primaryKeyword: "grease trap cleaning edmonton",
    secondaryKeywords: "commercial grease trap cleaning edmonton, grease trap pumping edmonton, grease trap service edmonton",
    targetArea: "Edmonton, AB",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "40.0",
    keywordDifficulty: "10.0",
    cpc: "4.0",
    priority: "High",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Hydro Jetting Edmonton | Drain & Sewer Jetting",
    pageSlug: "/hydro-jetting-edmonton",
    primaryKeyword: "hydro jetting edmonton",
    secondaryKeywords: "hydro jetting service edmonton, drain jetting edmonton, sewer jetting edmonton",
    targetArea: "Edmonton, AB",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "40.0",
    keywordDifficulty: "2.0",
    cpc: "2.0",
    priority: "High",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Commercial Kitchen Cleaning Airdrie | Hood & Exhaust",
    pageSlug: "/commercial-kitchen-cleaning-airdrie",
    primaryKeyword: "commercial kitchen cleaning airdrie",
    secondaryKeywords: "commercial kitchen cleaning services airdrie, restaurant kitchen cleaning airdrie, hood cleaning airdrie",
    targetArea: "Airdrie, AB",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "150.0",
    keywordDifficulty: "0.0",
    cpc: "2.0",
    priority: "Top Priority",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Hood Cleaning Edmonton | Commercial & Restaurant",
    pageSlug: "/hood-cleaning-edmonton",
    primaryKeyword: "hood cleaning edmonton",
    secondaryKeywords: "commercial hood cleaning edmonton, restaurant hood cleaning edmonton, kitchen hood cleaning edmonton",
    targetArea: "Edmonton, AB",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "10.0",
    keywordDifficulty: "2.0",
    cpc: "1.5",
    priority: "Medium",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Grease Trap Cleaning Vancouver | Commercial Kitchens",
    pageSlug: "/grease-trap-cleaning-vancouver",
    primaryKeyword: "grease trap cleaning vancouver",
    secondaryKeywords: "commercial grease trap cleaning vancouver, grease trap pumping vancouver, grease trap service vancouver",
    targetArea: "Vancouver, BC",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "70.0",
    keywordDifficulty: "0.0",
    cpc: "4.0",
    priority: "High",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Kitchen Exhaust & Restaurant Hood Cleaning Vancouver",
    pageSlug: "/kitchen-exhaust-cleaning-vancouver",
    primaryKeyword: "kitchen exhaust cleaning vancouver",
    secondaryKeywords: "restaurant hood cleaning vancouver, restaurant exhaust cleaning vancouver, commercial hood cleaning vancouver",
    targetArea: "Vancouver, BC",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "20.0",
    keywordDifficulty: "4.0",
    cpc: "3.0",
    priority: "High",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Hydro Jetting Vancouver | Drain & Sewer Jetting",
    pageSlug: "/hydro-jetting-vancouver",
    primaryKeyword: "hydro jetting vancouver",
    secondaryKeywords: "hydro jetting service vancouver, drain jetting vancouver, sewer jetting vancouver",
    targetArea: "Vancouver, BC",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "40.0",
    keywordDifficulty: "2.0",
    cpc: "2.0",
    priority: "High",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Hydro Jetting White Rock | Drain & Sewer Jetting",
    pageSlug: "/hydro-jetting-white-rock",
    primaryKeyword: "hydro jetting white rock",
    secondaryKeywords: "hydro jetting service white rock, drain jetting white rock, sewer jetting white rock",
    targetArea: "White Rock, BC",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "60.0",
    keywordDifficulty: "1.0",
    cpc: "2.0",
    priority: "High",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Hydro Jetting Coquitlam | Drain & Sewer Jetting",
    pageSlug: "/hydro-jetting-coquitlam",
    primaryKeyword: "hydro jetting coquitlam",
    secondaryKeywords: "hydro jetting service coquitlam, drain jetting coquitlam, sewer jetting coquitlam",
    targetArea: "Coquitlam, BC",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "60.0",
    keywordDifficulty: "1.0",
    cpc: "2.0",
    priority: "High",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Grease Trap Cleaning Victoria | Commercial Kitchens",
    pageSlug: "/grease-trap-cleaning-victoria",
    primaryKeyword: "grease trap cleaning victoria",
    secondaryKeywords: "commercial grease trap cleaning victoria, grease trap pumping victoria, grease trap service victoria",
    targetArea: "Victoria, BC",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "20.0",
    keywordDifficulty: "0.0",
    cpc: "1.9",
    priority: "High",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Hydro Jetting Surrey | Drain & Sewer Jetting",
    pageSlug: "/hydro-jetting-surrey",
    primaryKeyword: "hydro jetting surrey",
    secondaryKeywords: "hydro jetting service surrey, drain jetting surrey, sewer jetting surrey",
    targetArea: "Surrey, BC",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "20.0",
    keywordDifficulty: "1.0",
    cpc: "1.5",
    priority: "Medium",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Commercial Kitchen Cleaning Kelowna | Hood & Exhaust",
    pageSlug: "/commercial-kitchen-cleaning-kelowna",
    primaryKeyword: "commercial kitchen cleaning kelowna",
    secondaryKeywords: "restaurant kitchen cleaning kelowna, hood cleaning kelowna, kitchen exhaust cleaning kelowna",
    targetArea: "Kelowna, BC",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "10.0",
    keywordDifficulty: "1.0",
    cpc: "2.0",
    priority: "Medium",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Kitchen Exhaust Cleaning Winnipeg | Restaurant Hoods",
    pageSlug: "/kitchen-exhaust-cleaning-winnipeg",
    primaryKeyword: "kitchen exhaust cleaning winnipeg",
    secondaryKeywords: "hood cleaning winnipeg, restaurant hood cleaning winnipeg, commercial kitchen exhaust cleaning winnipeg",
    targetArea: "Winnipeg, MB",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "70.0",
    keywordDifficulty: "0.0",
    cpc: "2.5",
    priority: "High",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Hood Cleaning Winnipeg | Commercial & Restaurant",
    pageSlug: "/hood-cleaning-winnipeg",
    primaryKeyword: "hood cleaning winnipeg",
    secondaryKeywords: "commercial hood cleaning winnipeg, restaurant hood cleaning winnipeg, kitchen hood cleaning winnipeg",
    targetArea: "Winnipeg, MB",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "50.0",
    keywordDifficulty: "2.0",
    cpc: "1.5",
    priority: "High",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Grease Trap Cleaning Winnipeg | Commercial Kitchens",
    pageSlug: "/grease-trap-cleaning-winnipeg",
    primaryKeyword: "grease trap cleaning winnipeg",
    secondaryKeywords: "commercial grease trap cleaning winnipeg, grease trap pumping winnipeg, grease trap service winnipeg",
    targetArea: "Winnipeg, MB",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "60.0",
    keywordDifficulty: "1.0",
    cpc: "2.5",
    priority: "High",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Grease Trap Installation Winnipeg",
    pageSlug: "/grease-trap-installation-winnipeg",
    primaryKeyword: "grease trap installation winnipeg",
    secondaryKeywords: "winnipeg grease trap installation, grease interceptor installation winnipeg",
    targetArea: "Winnipeg, MB",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "40.0",
    keywordDifficulty: "1.0",
    cpc: "1.7",
    priority: "High",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Kitchen Exhaust Cleaning Brandon | Restaurant Hoods",
    pageSlug: "/kitchen-exhaust-cleaning-brandon",
    primaryKeyword: "kitchen exhaust cleaning brandon",
    secondaryKeywords: "hood cleaning brandon, commercial kitchen exhaust cleaning brandon",
    targetArea: "Brandon, MB",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "30.0",
    keywordDifficulty: "0.0",
    cpc: "2.0",
    priority: "High",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Hydro Jetting Montreal | Drain & Sewer Jetting",
    pageSlug: "/hydro-jetting-montreal",
    primaryKeyword: "hydro jetting montreal",
    secondaryKeywords: "hydro jetting service montreal, drain jetting montreal, sewer jetting montreal",
    targetArea: "Montreal, QC",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "50.0",
    keywordDifficulty: "2.0",
    cpc: "1.5",
    priority: "High",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Grease Trap Cleaning Montreal | Commercial Kitchens",
    pageSlug: "/grease-trap-cleaning-montreal",
    primaryKeyword: "grease trap cleaning montreal",
    secondaryKeywords: "commercial grease trap cleaning montreal, grease trap pumping montreal, grease trap service montreal",
    targetArea: "Montreal, QC",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "10.0",
    keywordDifficulty: "1.0",
    cpc: "1.3",
    priority: "Medium",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Hydro Jetting Laval | Drain & Sewer Jetting",
    pageSlug: "/hydro-jetting-laval",
    primaryKeyword: "hydro jetting laval",
    secondaryKeywords: "hydro jetting service laval, drain jetting laval, sewer jetting laval",
    targetArea: "Laval, QC",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "10.0",
    keywordDifficulty: "1.0",
    cpc: "1.5",
    priority: "Medium",
    ctaStrategy: "Call 1-888-328-8990",
  },
  {
    pageTitle: "Hydro Jetting Saskatoon | Drain & Sewer Jetting",
    pageSlug: "/hydro-jetting-saskatoon",
    primaryKeyword: "hydro jetting saskatoon",
    secondaryKeywords: "hydro jetting service saskatoon, drain jetting saskatoon, sewer jetting saskatoon",
    targetArea: "Saskatoon, SK",
    pageType: "City Service Page",
    searchIntent: "Local Trans.",
    volumePerMonth: "10.0",
    keywordDifficulty: "1.0",
    cpc: "1.5",
    priority: "Medium",
    ctaStrategy: "Call 1-888-328-8990",
  },
];

function priorityScore(priority: string) {
  return {
    "Top Priority": 0,
    "High": 1,
    "Medium": 2,
    "Low": 3,
    "P1": 0,
    "P2": 1,
    "P3": 2,
  }[priority] ?? 99;
}

export const SERVICE_HUBS = SEO_PAGES.filter((page) => ["Service Pillar", "Near Me Page", "Cost Guide"].includes(page.pageType))
  .slice()
  .sort((a, b) => priorityScore(a.priority) - priorityScore(b.priority) || Number.parseFloat(b.volumePerMonth) - Number.parseFloat(a.volumePerMonth))
  .slice(0, 12);

export const CITY_PAGES = SEO_PAGES.filter((page) => page.pageType === "City Service Page");

export const BLOG_POSTS: SeoPage[] = [
  {
    pageTitle: "How Often Should a Grease Trap Be Cleaned?",
    pageSlug: "/blog/how-often-should-a-grease-trap-be-cleaned",
    primaryKeyword: "grease trap cleaning frequency",
    secondaryKeywords: "grease trap maintenance schedule, how often to clean grease trap, commercial grease trap service",
    targetArea: "Canada (National)",
    pageType: "Insight Guide",
    searchIntent: "Informational",
    volumePerMonth: "120.0",
    keywordDifficulty: "12.0",
    cpc: "2.0",
    priority: "High",
    ctaStrategy: "Educational guide with call CTA",
  },
  {
    pageTitle: "Signs Your Catch Basin Needs Immediate Cleaning",
    pageSlug: "/blog/catch-basin-cleaning-signs",
    primaryKeyword: "catch basin cleaning signs",
    secondaryKeywords: "storm drain backup signs, catch basin odor, parking lot drain maintenance",
    targetArea: "Canada (National)",
    pageType: "Insight Guide",
    searchIntent: "Informational",
    volumePerMonth: "80.0",
    keywordDifficulty: "10.0",
    cpc: "2.0",
    priority: "High",
    ctaStrategy: "Educational guide with call CTA",
  },
  {
    pageTitle: "What Hydro Jetting Solves Better Than Snaking",
    pageSlug: "/blog/hydro-jetting-vs-snaking",
    primaryKeyword: "hydro jetting vs snaking",
    secondaryKeywords: "sewer jetting benefits, drain cleaning methods, high pressure drain cleaning",
    targetArea: "Canada (National)",
    pageType: "Insight Guide",
    searchIntent: "Informational",
    volumePerMonth: "90.0",
    keywordDifficulty: "14.0",
    cpc: "2.5",
    priority: "High",
    ctaStrategy: "Educational guide with call CTA",
  },
  {
    pageTitle: "Why Hood Cleaning Protects Restaurant Operations",
    pageSlug: "/blog/why-hood-cleaning-matters",
    primaryKeyword: "why hood cleaning matters",
    secondaryKeywords: "commercial hood cleaning benefits, NFPA 96 hood cleaning, kitchen exhaust safety",
    targetArea: "Canada (National)",
    pageType: "Insight Guide",
    searchIntent: "Informational",
    volumePerMonth: "70.0",
    keywordDifficulty: "11.0",
    cpc: "2.0",
    priority: "High",
    ctaStrategy: "Educational guide with call CTA",
  },
  {
    pageTitle: "Grease Trap Installation: When Replacement Beats Repair",
    pageSlug: "/blog/grease-trap-installation-vs-repair",
    primaryKeyword: "grease trap installation vs repair",
    secondaryKeywords: "grease interceptor replacement, grease trap cost comparison, commercial kitchen planning",
    targetArea: "Canada (National)",
    pageType: "Insight Guide",
    searchIntent: "Informational",
    volumePerMonth: "60.0",
    keywordDifficulty: "9.0",
    cpc: "2.0",
    priority: "Medium",
    ctaStrategy: "Educational guide with call CTA",
  },
  {
    pageTitle: "Preparing a Commercial Kitchen for Service Day",
    pageSlug: "/blog/preparing-commercial-kitchen-for-service",
    primaryKeyword: "commercial kitchen service preparation",
    secondaryKeywords: "restaurant prep checklist, kitchen exhaust access, grease service readiness",
    targetArea: "Canada (National)",
    pageType: "Insight Guide",
    searchIntent: "Informational",
    volumePerMonth: "50.0",
    keywordDifficulty: "8.0",
    cpc: "1.8",
    priority: "Medium",
    ctaStrategy: "Educational guide with call CTA",
  },
];

export function getSiteUrl() {
  return DEFAULT_SITE_URL;
}

export function absoluteUrl(path: string) {
  const base = getSiteUrl().replace(/\/+$/, "");
  return `${base}${toPath(path)}`;
}

export function toPath(path: string) {
  return path.startsWith("/") ? path : `/${path}`;
}

export function bySlug(slug: string) {
  return SEO_PAGES.find((page) => page.pageSlug.replace(/^\/+/, "") === slug) ?? null;
}

export function cityFromTargetArea(targetArea: string) {
  return targetArea.includes(",") ? targetArea.split(",")[0].trim() : targetArea.replace(/\s*\([^)]*\)$/, "");
}

export function relatedPages(page: SeoPage, limit = 12) {
  const pageProvince = page.targetArea.split(",").slice(1).join(",").trim();
  return SEO_PAGES.filter((candidate) => candidate.pageSlug !== page.pageSlug)
    .map((candidate) => {
      let score = 0;
      if (candidate.pageType === page.pageType) score += 4;
      if (candidate.targetArea === page.targetArea) score += 4;
      if (pageProvince && candidate.targetArea.includes(pageProvince)) score += 2;
      if (candidate.priority === page.priority) score += 1;
      if (candidate.primaryKeyword.split(" ")[0] === page.primaryKeyword.split(" ")[0]) score += 1;
      return { candidate, score };
    })
    .sort((a, b) => b.score - a.score || priorityScore(a.candidate.priority) - priorityScore(b.candidate.priority))
    .slice(0, limit)
    .map(({ candidate }) => candidate);
}

export function formatPriority(priority: string) {
  return priority.replace(/Priority$/i, "priority");
}
